### ISSUE TITLE
axis change is different

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/ECLASS-Report-Generator#15]
- Here again, I am seeing meaningfully different things on these graphs than what Ben originally sent out.  For example, the axis on the 'change in interest in physics' graph is reversed, but the trend is not

**Comment by mnky9800n** [comment]
This could be due to the qualtrics data being numeric and I got the numbers backwards. For instance, the error seems to occur in the "current interest" question as well. The responses are numbered 1-5 but I guessed which at 1 is "very low" and 5 is "very high". So maybe I guessed wrong. Can you confirm that I guessed wrong?

**Comment by wilcoxbeth** [comment]
For the current interest, you are correct 1=very low and 5=very high.
For the change in interest, 1=increased, 2=stayed the same, 3=decreased

**Comment by mnky9800n** [comment]
That means that for current I am right, for change in interest I am incorrect. I will fix this.
