### ISSUE TITLE
table 1 issue

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/ECLASS-Report-Generator#4]
originally submitted via email:

Overall Results table:
- Not currently populated.  Is this related to the issues you have been having connecting the instructors survey to the individual courses?

**Comment by mnky9800n** [comment]
Yeah this is connected. I've been waiting to implement the functionality until we figure out how we are going to associate instructors to surveys

**Comment by wilcoxbeth** [comment]
Great.  Let me know if you need anything else from me to facilitate this.

**Comment by mnky9800n** [comment]
Ok, I think I need to look on the server for how data is named. Do you have this documented anywhere (it's okay if you don't). Maybe we could write a wiki page for this in the repository wiki.

**Comment by wilcoxbeth** [comment]
We don't have this documented as far as I know.  

You assigned this one to me.  What would you like me to do to address this?

**Comment by mnky9800n** [comment]
I'm going to reassign this to me because I think I should figure it out.
