### ISSUE TITLE
personal pre/post shifts

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/ECLASS-Report-Generator#5]
- Why are some of the arrows green and some red?  Is it direction (i.e., positive shifts are green and negative are red)?  This might be somewhat confusing as some of the dots are red, but none of the dots are green.  For sure, if we keep it, it should be put in the caption.

**Comment by mnky9800n** [comment]
Yeah, I made positive shifts green and negative shifts red but I'm not sure I like this feature or not either.

Pros:
- easier to see positive shifts (especially if you make everything green not just the arrow)

Cons:
- bad for color blindedness
- makes the plots even more cluttered

**Comment by wilcoxbeth** [comment]
Hmmm.  I guess I am inclined to go with simplicity.  It is a nice feature to highlight positive shifts, but I think it is not worth the extra complexity.  Lets just leave the arrows the color of the dots.

**Comment by mnky9800n** [comment]
It might be worth it to leave the logic in to use in a publication. I'm going close this issue for now because I have addressed it in the code.
