### ISSUE TITLE
grades plot

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/ECLASS-Report-Generator#6]
originally submitted via email.
- The caption says 'An ordered plot', but the plot is not currently ordered

**Comment by mnky9800n** [comment]
Do you want to order the plots by value? I think this is the real question we should ask here. I'm fine with doing it this way but it's your decision.

**Comment by wilcoxbeth** [comment]
I don't feel strongly about it, but Heather in the past has expressed a strong preference for the ordered plots.  She finds them less visually overwhelming.  So lets go with that

**Comment by mnky9800n** [comment]
Ok, as a test I will sort the graded plots, if that works I';ll do the other itemized plots.
