### ISSUE TITLE
experimental physicist vs you plot

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/ECLASS-Report-Generator#7]
For the experimental physicist vs you graphs:
- The caption says green vs. red in the plots, but the points are still red and blue (and now potentially even more confusing with the green arrows)

**Comment by mnky9800n** [comment]
Blue and red is better for color blindedness. We could change the color scheme totally and do gold and black (CU colors) and have some school spirit. I'm assuming it was originally red and blue in some graphs and red and green in different graphs to highlight that the plots were of different things. What do you think?

**Comment by wilcoxbeth** [comment]
I agree that the red and green thing is probably a bad idea, but I also think it is good to have a visual distinction between the different plots.  
How about red and black (or dark grey) for the experimental physicist vs. you graphs?

**Comment by mnky9800n** [comment]
I addressed both these issues. Hopefully they are resolved.
