### ISSUE TITLE
get rid of confidence intervals for non-itemized questions

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/ECLASS-Report-Generator#8]
For the extra questions:
- I think I agree that confidence intervals are not really needed on most of these.  I can't really think of a reason why an instructor would need them since there are no inferences being made based on these data.

**Comment by wilcoxbeth** [comment]
I chatted with Heather about this also and she agreed that confidence intervals were not necessary for the questions reporting demographics of the participants (eg. gender, major, and future plans)

**Comment by mnky9800n** [comment]
Ok I made the changes. We can reopen this issue if we find any discrepancies in the new reports.
